In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
from sklearn.pipeline import make_pipeline

In [3]:
#data creation
water=np.array([10,20,30,40]).reshape(-1,1)
fertilizer=np.array([1,2,3,4]).reshape(-1,1)
crop_yield=np.array([1,4,8,16]).reshape(-1,1)
x=np.concatenate([water,fertilizer],axis=1)
y=crop_yield.copy()

In [5]:
w2=np.array([10,20,30,40])
print(w2)
print(w2.shape)

[10 20 30 40]
(4,)


In [8]:
w3=np.array([10,20,30,40]).reshape(-1,1)
print(w3)
print(w3.shape)

[[10]
 [20]
 [30]
 [40]]
(4, 1)


In [9]:
x  # indipendent variable

array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4]])

In [10]:
y #dependent variable

array([[ 1],
       [ 4],
       [ 8],
       [16]])

In [12]:
x_test=np.array([[35,12],[11,1.2],[26,5.8]]).reshape(3,2)
x_test
print(x_test.shape)

(3, 2)


In [13]:
#Transerfer
np.set_printoptions(suppress=True)

In [14]:
#creat new features
f=PolynomialFeatures(degree=2)
f_new=f.fit_transform(x)
f_new

array([[   1.,   10.,    1.,  100.,   10.,    1.],
       [   1.,   20.,    2.,  400.,   40.,    4.],
       [   1.,   30.,    3.,  900.,   90.,    9.],
       [   1.,   40.,    4., 1600.,  160.,   16.]])

In [15]:
#pipeline and fit
model=make_pipeline(PolynomialFeatures(degree=2),linear_model.LinearRegression())
model.fit(x,y)
# 2 features then degree2- 5 features than linear model.

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('linearregression', LinearRegression())])

In [16]:
y_pred=model.predict(x_test)
y_pred

array([[12.10834684],
       [ 1.27755308],
       [ 6.25351423]])